### ISSUE TITLE
Return nil if no avatar

### ISSUE THREAD

**Issue by uberllama** [chrislloyd/gravtastic#8]
Cheers for the plugin. Would be great to receive nil if the user doesn't have an avatar on gravatar, so that we can supply our own default or alternative, rather than just displaying the gravatar default.

**Comment by nlib** [comment]
Agreed. It doesn't make much sense this way. Why not just return nil or false, instead of having us parse a URL?  

When I set the default option, it currently returns something like this:

"https://secure.gravatar.com/avatar/489b7ead8bb3967592a4c6a850077502.png?d=https://default_url.com&r=PG"

Why? And how do I handle this? Just pare the URL?
